[MM-853]: Added server testcases for store/subscription_store.go
Brightscout/mattermost-plugin-mscalendar pull request #22
Opened 2024-10-15 07:41 UTC by Kshitij-Katiyar

### Summary
Added server testcases for store/subscription_store.go

2024-11-12 07:57 UTC, raghavaggarwal2308 requested changes

2024-11-12 07:57 UTC, raghavaggarwal2308 commented on calendar/store/subscription_store_test.go
> +	mockAPI, store, _, _, _ := GetMockSetup(t)
move this inside

2024-11-12 07:57 UTC, raghavaggarwal2308 commented on calendar/store/subscription_store_test.go
> +				mockAPI.On("KVGet", mock.Anything).Return(nil, &model.AppError{Message: "Subscription not found"}).Times(1)
pass proper value

2024-11-12 07:57 UTC, raghavaggarwal2308 commented on calendar/store/subscription_store_test.go
> +				mockAPI.On("KVGet", mock.Anything).Return([]byte(`{"PluginVersion":"1.0","Remote":{"ID":"mockRemoteID","CreatorID":"mockCreatorID"}}`), nil).Times(1)
Create util for response value

2024-11-12 07:57 UTC, raghavaggarwal2308 commented on calendar/store/subscription_store_test.go
> +	mockAPI, store, mockLogger, mockLoggerWith, _ := GetMockSetup(t)
move inside

2024-11-12 07:57 UTC, raghavaggarwal2308 commented on calendar/store/subscription_store_test.go
> +	mockUser := &User{MattermostUserID: "user1", Settings: Settings{EventSubscriptionID: "mockEventSubscriptionID"}, Remote: &remote.User{ID: "mockRemoteUserID"}}
I think we created a util for this?

2024-11-12 14:12 UTC, Kshitij-Katiyar commented on calendar/store/subscription_store_test.go
> +				mockAPI.On("KVGet", mock.Anything).Return([]byte(`{"PluginVersion":"1.0","Remote":{"ID":"mockRemoteID","CreatorID":"mockCreatorID"}}`), nil).Times(1)
used only once

2024-11-12 14:18 UTC, Kshitij-Katiyar commented on calendar/store/subscription_store_test.go
> +				mockAPI.On("KVGet", mock.Anything).Return(nil, &model.AppError{Message: "Subscription not found"}).Times(1)
generated at run time with random values

2024-11-14 07:46 UTC, raghavaggarwal2308 approved these changes

2024-11-18 10:40 UTC, merged